# Generated by Django 5.0.3 on 2024-03-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_article_image_alter_recipe_body_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='description_text',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
    ]
