# Generated by Django 5.0.3 on 2024-03-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_about_description_text_remove_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='body_image',
            field=models.ImageField(blank=True, default='recipe/body_image/default.jpg', editable=False, upload_to='recipe/body_image/'),
            preserve_default=False,
        ),
    ]
