# Generated by Django 5.0.3 on 2024-03-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_body_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='preview_article',
            field=models.ImageField(blank=True, editable=False, upload_to='articles_images/'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles_images/'),
        ),
    ]
