# Generated by Django 5.0.3 on 2024-03-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_aboutsection_preview_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='preview_article',
        ),
        migrations.AddField(
            model_name='article',
            name='preview_article',
            field=models.ImageField(blank=True, editable=False, upload_to='articles_images/'),
        ),
    ]
